/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


export const styles:any[] = [''];
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiRDovVHVnYXMvUGVtcm9ncmFtYW4gV2ViIExhbmp1dC9iZWxhamFyYW5ndWxhci9kZXBsb3ktZGVtby9zcmMvYXBwL25hdmJhci9uYXZiYXIuY29tcG9uZW50LmNzcy5zaGltLm5nc3R5bGUudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9EOi9UdWdhcy9QZW1yb2dyYW1hbiBXZWIgTGFuanV0L2JlbGFqYXJhbmd1bGFyL2RlcGxveS1kZW1vL3NyYy9hcHAvbmF2YmFyL25hdmJhci5jb21wb25lbnQuY3NzIl0sInNvdXJjZXNDb250ZW50IjpbIiAiXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7OzsifQ==
