/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


export const styles:any[] = [''];
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiRDovVHVnYXMvUGVtcm9ncmFtYW4gV2ViIExhbmp1dC9iZWxhamFyYW5ndWxhci9kZXBsb3ktZGVtby9zcmMvYXBwL2hvbWUvaG9tZS5jb21wb25lbnQuY3NzLnNoaW0ubmdzdHlsZS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL0Q6L1R1Z2FzL1BlbXJvZ3JhbWFuIFdlYiBMYW5qdXQvYmVsYWphcmFuZ3VsYXIvZGVwbG95LWRlbW8vc3JjL2FwcC9ob21lL2hvbWUuY29tcG9uZW50LmNzcyJdLCJzb3VyY2VzQ29udGVudCI6WyIgIl0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7In0=
